#
# Create the custom Jenkins image on the compute nodes to avoid
# setting up a custom repository.
#
- hosts: nodes
  become: yes
  tasks:
    - name: Copying Jenkins container context
      copy:
        src: ./jenkins.docker
        dest: /tmp/jenkins.docker
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: u+rw,g-wx,o-rwx

    - name: Building Jenkins container
      command: docker build -f /tmp/jenkins.docker -t my/jenkins-image:1.0 .

- hosts: control-plane
  tasks:
    - name: Setup Jenkins namespace
      command: kubectl create namespace jenkins

    - name: Copying Jenkins deployment YAML descriptor
      copy:
        src: ./jenkins-deployment.yml
        dest: /tmp/jenkins-deployment.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: u+rw,g-wx,o-rwx

    - name: Deploying Jenkins instance
      shell: kubectl create -f /tmp/jenkins-deployment.yml -n jenkins
      
    - name: Copying Jenkins service YAML descriptor
      copy:
        src: ./jenkins-service.yml
        dest: /tmp/jenkins-service.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: u+rw,g-wx,o-rwx

    - name: Setting up Jenkins service
      shell: kubectl create -f /tmp/jenkins-service.yml -n jenkins
